name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: maven
      - name: Start RabbitMQ
        uses: namoshek/rabbitmq-github-action@v1
        with:
          version: '3.8.9'
          ports: '5672:5672'
          container-name: 'rabbitmq'
      - name: Copy config file
        run: cp src/main/resources/app-pipeline.config src/main/resources/app.config
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
    
